# Generated by Django 5.1.5 on 2025-01-28 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bagian',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Keluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.CharField(max_length=15, unique=True)),
                ('penerima_surat', models.CharField(max_length=100)),
                ('tanggal_kirim', models.DateField()),
                ('tanggal_surat', models.DateField()),
                ('nomor_surat', models.CharField(max_length=15)),
                ('judul_surat', models.CharField(max_length=100)),
                ('tujuan_surat', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('berkas_surat', models.FileField(blank=True, null=True, upload_to='berkas/')),
            ],
            options={
                'verbose_name': 'Surat Keluar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disposisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_menerima', models.DateField()),
                ('nomor_agenda', models.CharField(max_length=15)),
                ('perihal', models.TextField()),
                ('tanggal_surat', models.DateField()),
                ('nomor_surat', models.CharField(max_length=15)),
                ('asal_surat', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('RA', 'Rahasia'), ('SR', 'Sangat Rahasia'), ('PG', 'Penting'), ('SP', 'Sangat Penting'), ('RT', 'Rutin'), ('BS', 'Biasa')], default='BS', max_length=2)),
                ('diteruskan_ke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposisi', to='perkamen.divisi')),
            ],
            options={
                'verbose_name': 'Disposisi',
                'ordering': ['-tanggal_menerima'],
            },
        ),
        migrations.CreateModel(
            name='Masuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.CharField(max_length=15, unique=True)),
                ('berkas', models.FileField(blank=True, null=True, upload_to='berkas/')),
                ('disposisi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surat', to='perkamen.disposisi')),
            ],
            options={
                'verbose_name': 'Surat Masuk',
                'ordering': ['-created_at'],
            },
        ),
    ]
